apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cntk-consolelink
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 1-infra/consolelink
    repoURL: https://github.com/ldean0558/multi-tenancy-gitops.git
    targetRevision: demo-mq-v2-ldean0558
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
