apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  labels:
    gitops.tier.group: cntk
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openldap
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: 2-services/instances/openldap
    repoURL: https://github.com/ldean0558/multi-tenancy-gitops.git
    targetRevision: demo-mq-v2-ldean0558
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
